// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYYceUNT_LpyV9Em_8SbTGggYWaJY8L_s',
    appId: '1:79340758252:web:b5d405267763acc7e271c9',
    messagingSenderId: '79340758252',
    projectId: 'fir-auth-a4bf5',
    authDomain: 'fir-auth-a4bf5.firebaseapp.com',
    storageBucket: 'fir-auth-a4bf5.appspot.com',
    measurementId: 'G-VD68JBK0JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVtDDWc2nuBWqXiShuD-NQTLL8Fk5ikyE',
    appId: '1:79340758252:android:94088f68ad02161de271c9',
    messagingSenderId: '79340758252',
    projectId: 'fir-auth-a4bf5',
    storageBucket: 'fir-auth-a4bf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSLfpSZwuIXkhHZglnIaOQdkFAKoEAviQ',
    appId: '1:79340758252:ios:6396c01a3e6f6b78e271c9',
    messagingSenderId: '79340758252',
    projectId: 'fir-auth-a4bf5',
    storageBucket: 'fir-auth-a4bf5.appspot.com',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSLfpSZwuIXkhHZglnIaOQdkFAKoEAviQ',
    appId: '1:79340758252:ios:2f4efc167bbaa7a2e271c9',
    messagingSenderId: '79340758252',
    projectId: 'fir-auth-a4bf5',
    storageBucket: 'fir-auth-a4bf5.appspot.com',
    iosBundleId: 'com.example.firebaseauth.RunnerTests',
  );
}
